INSERT INTO example.products (price, product_name, stock, credential) VALUES
                                                                          (19.99, 'Echo Dot (5ª Geração)', 50, gen_random_uuid()),
                                                                          (999.99, 'Apple iPhone 14 Pro Max', 30, gen_random_uuid()),
                                                                          (2499.99, 'Samsung Smart TV 65" 4K UHD', 20, gen_random_uuid()),
                                                                          (599.99, 'PlayStation 5', 15, gen_random_uuid()),
                                                                          (199.99, 'Kindle Paperwhite 11ª Geração', 40, gen_random_uuid()),
                                                                          (49.99, 'Mouse Gamer Logitech G502 Hero', 60, gen_random_uuid()),
                                                                          (29.99, 'Teclado Mecânico Redragon Kumara', 55, gen_random_uuid()),
                                                                          (119.99, 'Fone de Ouvido Bluetooth Sony WH-CH510', 25, gen_random_uuid()),
                                                                          (449.99, 'Monitor Gamer LG UltraGear 27"', 35, gen_random_uuid()),
                                                                          (329.99, 'Smartwatch Samsung Galaxy Watch 5', 45, gen_random_uuid()),
                                                                          (39.99, 'Carregador Portátil Xiaomi Mi Power Bank 10000mAh', 70, gen_random_uuid()),
                                                                          (89.99, 'Aspirador de Pó Vertical Electrolux', 20, gen_random_uuid()),
                                                                          (159.99, 'Cadeira Gamer ThunderX3', 10, gen_random_uuid()),
                                                                          (229.99, 'Roteador Mesh TP-Link Deco M5', 25, gen_random_uuid()),
                                                                          (79.99, 'Fire TV Stick 4K', 50, gen_random_uuid()),
                                                                          (49.99, 'Alexa Echo Show 5', 40, gen_random_uuid()),
                                                                          (349.99, 'GoPro Hero 11 Black', 12, gen_random_uuid()),
                                                                          (179.99, 'Tablet Samsung Galaxy Tab A8', 30, gen_random_uuid()),
                                                                          (1399.99, 'Notebook Dell Inspiron 15', 20, gen_random_uuid()),
                                                                          (1099.99, 'MacBook Air M1 256GB', 15, gen_random_uuid()),
                                                                          (239.99, 'Impressora Multifuncional HP Ink Tank', 25, gen_random_uuid()),
                                                                          (69.99, 'Relógio Inteligente Amazfit Bip U', 40, gen_random_uuid()),
                                                                          (29.99, 'Mouse Sem Fio Logitech M170', 80, gen_random_uuid()),
                                                                          (24.99, 'Carregador Rápido USB-C Anker 20W', 90, gen_random_uuid()),
                                                                          (319.99, 'Processador AMD Ryzen 5 5600X', 20, gen_random_uuid()),
                                                                          (499.99, 'Placa de Vídeo NVIDIA RTX 3060', 10, gen_random_uuid()),
                                                                          (129.99, 'Gabinete Gamer Cooler Master', 30, gen_random_uuid()),
                                                                          (299.99, 'Fonte Corsair 750W 80 Plus Gold', 15, gen_random_uuid()),
                                                                          (399.99, 'Monitor UltraWide LG 29" Full HD', 25, gen_random_uuid()),
                                                                          (699.99, 'Smartphone Xiaomi Redmi Note 12', 30, gen_random_uuid()),
                                                                          (179.99, 'Caixa de Som JBL Flip 6', 35, gen_random_uuid()),
                                                                          (219.99, 'Headset Gamer Razer Kraken', 20, gen_random_uuid()),
                                                                          (74.99, 'HD Externo Seagate 2TB', 45, gen_random_uuid()),
                                                                          (39.99, 'Pendrive Kingston 128GB USB 3.0', 70, gen_random_uuid()),
                                                                          (109.99, 'SSD Kingston NV2 500GB M.2', 50, gen_random_uuid()),
                                                                          (29.99, 'Câmera de Segurança Wi-Fi Intelbras', 55, gen_random_uuid()),
                                                                          (549.99, 'Microfone Shure SM7B', 10, gen_random_uuid()),
                                                                          (1399.99, 'Placa de Vídeo NVIDIA RTX 4070 Ti', 5, gen_random_uuid()),
                                                                          (249.99, 'Controle Xbox Series X Original', 30, gen_random_uuid()),
                                                                          (29.99, 'Tripé para Câmera e Celular', 50, gen_random_uuid()),
                                                                          (79.99, 'Filtro de Linha APC com Proteção contra Surtos', 40, gen_random_uuid()),
                                                                          (99.99, 'Ventilador de Mesa Arno Turbo', 25, gen_random_uuid()),
                                                                          (54.99, 'Lâmpada Inteligente Wi-Fi Positivo', 60, gen_random_uuid()),
                                                                          (699.99, 'Console Xbox Series X', 20, gen_random_uuid()),
                                                                          (1899.99, 'Notebook Lenovo Ideapad 3 Ryzen 7', 15, gen_random_uuid()),
                                                                          (99.99, 'Smartband Xiaomi Mi Band 7', 45, gen_random_uuid()),
                                                                          (459.99, 'Máquina de Café Nespresso Essenza Mini', 25, gen_random_uuid());
